version: '3.8'

services:
  nest:
    build: .
    image: nest_app
    container_name: nest_app
    volumes:
      - .:/usr/app
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
    restart: on-failure
    networks:
      - my_network
  postgres:
    build:
      dockerfile: ./postgres/Dockerfile
      context: .
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - my_network
networks:
  my_network:
      driver: bridge
volumes:
  postgres_data:

